context:
  version: 5.0.0

package:
  name: jolt-physics
  version: ${{ version }}

source:
  url: https://github.com/jrouwe/JoltPhysics/archive/refs/tags/v${{ version }}.zip
  sha256: 2c98750316d565d553cb2c15d494b6b2ea4fbe55eb2ca18df536c9f4ac340d36

requirements: 
  build: 
    - ${{ compiler("cxx") }}
    - cmake
    - ninja

build:
  number: 0
  script:
    - if: win
      then: |
        cmake -GNinja ^
            %CMAKE_ARGS% ^
            -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
            -DBUILD_SHARED_LIBS=ON ^
            -DCMAKE_BUILD_TYPE=Distribution ^
            -DCROSS_PLATFORM_DETERMINISTIC=ON ^
            -DTARGET_VIEWER=OFF ^
            -DTARGET_SAMPLES=OFF ^
            -DTARGET_HELLO_WORLD=OFF ^
            -DTARGET_UNIT_TESTS=OFF ^
            -S %SRC_DIR%\Build
        cmake --build . --target install
      else: |
        cmake -GNinja \
            $CMAKE_ARGS \
            -DCMAKE_INSTALL_PREFIX=$PREFIX \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Distribution \
            -DCROSS_PLATFORM_DETERMINISTIC=ON \
            -DTARGET_VIEWER=OFF \
            -DTARGET_SAMPLES=OFF \
            -DTARGET_HELLO_WORLD=OFF \
            -DTARGET_UNIT_TESTS=OFF \
            -S $SRC_DIR/Build
        cmake --build . --target install

about:
  homepage: https://github.com/jrouwe/JoltPhysics
  license: MIT
  license_file: LICENSE
  summary: A multi core friendly rigid body physics and collision detection library.
  description: A multi core friendly rigid body physics and collision detection library. Written in C++. Suitable for games and VR applications. Used by Horizon Forbidden West. 
  documentation: https://xtensor.readthedocs.iohttps://jrouwe.github.io/JoltPhysics/
  repository: https://github.com/jrouwe/JoltPhysics

extra:
  recipe-maintainers:
    - baszalmstra
